export { BloodType, BLOOD_TYPE_VALUES } from './blood-type.enum'
export { Department, DEPARTMENT_VALUES } from './department.enum'
export { Locale, LOCALE_VALUES } from './locale.enum'
export { PatientPriority, PATIENT_PRIORITY_VALUES } from './patient-priority.enum'
export { PatientStatus, PATIENT_STATUS_VALUES } from './patient-status.enum'
export { StorageKey } from './storage-key.enum'
export { Theme, THEME_VALUES } from './theme.enum'
